export const RACE_LIST_REQUEST = 'RACE_LIST_REQUEST'
export const RACE_LIST_SUCCESS = 'RACE_LIST_SUCCESS'
export const RACE_LIST_FAIL = 'RACE_LIST_FAIL'

export const SINGLE_RACE_REQUEST = 'SINGLE_RACE_REQUEST'
export const SINGLE_RACE_SUCCESS = 'SINGLE_RACE_SUCCESS'
export const SINGLE_RACE_FAIL = 'SINGLE_RACE_FAIL'
export const SINGLE_RACE_RESET = 'SINGLE_RACE_RESET'