export const RACE_LIST_REQUEST = 'RACE_LIST_REQUEST'
export const RACE_LIST_SUCCESS = 'RACE_LIST_SUCCESS'
export const RACE_LIST_FAIL = 'RACE_LIST_FAIL'

export const SINGLE_RACE_REQUEST = 'SINGLE_RACE_REQUEST'
export const SINGLE_RACE_SUCCESS = 'SINGLE_RACE_SUCCESS'
export const SINGLE_RACE_FAIL = 'SINGLE_RACE_FAIL'
export const SINGLE_RACE_RESET = 'SINGLE_RACE_RESET'

export const CREATE_STARTLIST_REQUEST = 'CREATE_STARTLIST_REQUEST'
export const CREATE_STARTLIST_SUCCESS = 'CREATE_STARTLIST_SUCCESS'
export const CREATE_STARTLIST_FAIL = 'CREATE_STARTLIST_FAIL'

export const CREATE_RESULTLIST_REQUEST = 'CREATE_RESULTLIST_REQUEST'
export const CREATE_RESULTLIST_SUCCESS = 'CREATE_RESULTLIST_SUCCESS'
export const CREATE_RESULTLIST_FAIL = 'CREATE_RESULTLIST_FAIL'

export const CREATE_RESULTINFO_REQUEST = 'CREATE_RESULTINFO_REQUEST'
export const CREATE_RESULTINFO_SUCCESS = 'CREATE_RESULTINFO_SUCCESS'
export const CREATE_RESULTINFO_FAIL = 'CREATE_RESULTINFO_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const SAVE_RESULT_REQUEST = 'SAVE_RESULT_REQUEST'
export const SAVE_RESULT_SUCCESS = 'SAVE_RESULT_SUCCESS'
export const SAVE_RESULT_FAIL = 'SAVE_RESULT_FAIL'